---
# This playbook will take care of all steps required to remove
# Insights Client
- name: Insights Remove
  hosts: localhost
  become: yes
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldVbENSMGx6ZG5jMU9FUXJhalZ3VGtGUmFWVlZlRUZCYjFwaVZG
      UTNPRmRxTXpGYVNHNTFWM2szU2twM01ISkRPRXB5ZDFaTFNYb0tUR0oxVDIxSGVTOTJUbE15SzJZ
      M1dqRXhZek5SZFVaMEx6Wnpja0pDSzFCVFl6Uk1WREZrWWtoaGEwUXZZMkY1TjFwVU16QkVkMnA1
      T1ZoUk1HdE1id28yZEVKeFRHZ3hTa3B5YURjeWNHOXVNRVl5V0RVNE1GUkRPVnA1UzIxU2JrWkhX
      VTVuTlVSUGIweEpObkJKVjFFclMxZDJibk5hZGtKak9YTXZaRVp6Q21WMlRuSnhhMk51VHpaVWNH
      aDFaRlpsVUZaeGVYZFlXbUowWWs5cFNtVnhhMWd6Um5rNWNFaHJiSFZ4VFhZMlZHWktWMDFCUjJ4
      cFRqWk9hVzVqT0V3S0sxSXlXVFk0WkZOc1NrNHZUME5WVlc5V1YwUlRVV2h1UXpkRVVXa3hiRnBx
      WVVscFVFUTBaREFyYW1sTlowNDFaa1IyYlU5aE1ERTBXbVZuWjB4Q09BcFVNME5UU1ZndlJ6SnhS
      V2xUV0hkUmJEQkhkWFZHVUhad2RXeEhOV3BwUVZOaGRGUXpiakZXYW5Bd0swMUljRk0zTDJKalZu
      WTROV1UxT0d0bk5VVm9DbVV2ZEZBNVlrZHdPSEZqVlVkdWIwdG9WVTlzTUhJdlpXdEhNRlUyVVhZ
      eVRYcEZTVVphV0hCMVNFSnJaa3MwVkhsaU1UWjZkbnBJVTFKaFZYZG9kbmdLTjBOalZEaHViRFZY
      TW5CbGVsWktjVFYxWWk5aFpHRmxTMUp2ZUVkb1FYbHdSWGw0ZDFCSk9GZFBZelIyUkRaWk5rZGhP
      RUZ4U0ZGVU1GbE5PVEEzUXdwNWFFcFdkVVpEYTNKMlNrbExlV3BZUW05alVYaGlSQ3N3VlZwRFJI
      Z3pkU3RwT0hneGVWWTRiSFJ3T1VaQ1JVOWthSGxuTnpWaFFsUmpRVFExTVU1UkNrcGlNa1JxUjJ4
      NFUzQnZXWGRpUzBNNWVFODFlSFpNVTFwR1lTc3haM2d6TUV0MGRFNUNjR2xKVEhwVU4yVmpSRFZM
      WW1oUldubDVUMWR2Wm0weWRWTUtkemhUZVdSaWJXcFpaMDlTYWpWWU4ybDJMMkZ6ZEhGMFJXNXpS
      a0YxSzB0SmRDc3ZlV3BOTUZwRmNXOUhRblJJTjIxU2NWbG5TREZSYTJGNVpIWlhUUW95ZDFKWFdq
      bHVkemxsVFQwS1BVa3hZMjhLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  tasks:
    - name: Unregister the insights-client
      command: insights-client --unregister
